version: '3.8'

services:
  logziojaegercollector:
    image: logzio/jaeger-logzio-collector:latest
    environment:
      - ACCOUNT_TOKEN=${LOGZIO_ACCOUNT_TOKEN}
      - REGION=${LOGZIO_REGION_CODE}
    networks:
      - net-logzio
    ports:
      - 14268:14268
      - 9411:9411
      - 14267:14267
      - 14269:14269
      - 14250:14250

  jaegeragent:
    image: jaegertracing/jaeger-agent:1.21
    networks:
      - net-logzio
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778/tcp
      - 5775:5775/udp
    command: --reporter.grpc.host-port=logziojaegercollector:14250
    depends_on:
      - logziojaegercollector

  dataapi:
    build:
      context: .
      dockerfile: ./src/DataApi/Dockerfile
    image: logziojaegersample-dataapi
    networks:
      - net-logzio
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jaeger__IsEnabled=true
      - Jaeger__AgentHost=jaegeragent
      - Jaeger__AgentPort=6831
    ports:
      - 8001:80
    depends_on:
      - jaegeragent

  businessapi:
    build:
      context: .
      dockerfile: ./src/BusinessApi/Dockerfile
    image: logziojaegersample-businessapi
    networks:
      - net-logzio
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jaeger__IsEnabled=true
    ports:
      - 8000:80
    depends_on:
      - jaegeragent

networks:
  net-logzio:
    external:
      name: net-logzio
