version: "3.8"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8180:80
    volumes:
      - /tmp/log/nginx:/var/log/nginx
    depends_on:
      - otelcol
  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otelcol
    command: ["--config=/etc/otel-collector-config.yml"]
    ports:
      - 13133:13133
      - 14250:14250
      - 14268:14268
      - 4317:4317
      - 6060:6060
      - 8888:8888
      - 7276:7276
      - 9943:9943
    volumes:
      - ./config/otel-collector.yaml:/etc/otel-collector-config.yml
      - /tmp/log/nginx:/tmp/log/nginx
    depends_on:
      - splunk
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=opentelemetry
    ports:
      - 8000:8000
      - 8088:8088
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ./config/splunk.yml:/tmp/defaults/default.yml
