receivers:
  otlp:
    protocols:
      grpc:

exporters:
  splunk_hec:
    token: "00000000-0000-0000-0000-0000000000000"
    endpoint: "http://host.docker.internal:8088/services/collector"
    source: "otel"
    sourcetype: "otel"
    max_connections: 20
    disable_compression: false
    timeout: 10s
    insecure_skip_verify: true
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [splunk_hec]
