receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  splunk_hec:
    token: "00000000-0000-0000-0000-0000000000000"
    endpoint: "http://splunk:8088/services/collector"
    source: "otel"
    sourcetype: "otel"
    max_connections: 20
    disable_compression: false
    timeout: 10s
    insecure_skip_verify: true
    insecure: true

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, splunk_hec]
