services:
  webapi:
    build:
      context: .
      dockerfile: ./src/WebApi/Dockerfile
    container_name: dotnetsamplewebapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft=Information
      - Application__EnforceHttps=false
      - OpenTelemetryTracing__Enabled=true
      - OpenTelemetryTracing__OtlpExporter__Endpoint=http://otelcollector:4317
    ports:
      - 8002:80
    depends_on:
      - otelcollector
  otelcollector:
    image: otel/opentelemetry-collector-contrib:0.26.0
    container_name: otelcollector
    command: ["--config=/etc/otel-collector-config.yml"]
    ports:
      - 13133:13133
      - 14250:14250
      - 14268:14268
      - 4317:4317
      - 6060:6060
      - 8888:8888
      - 7276:7276
      - 9943:9943
    volumes:
      - ./docker/otel-collector.yaml:/etc/otel-collector-config.yml
    depends_on:
      - splunk
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=opentelemetry
    ports:
      - 8000:8000
      - 8088:8088
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000']
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ./docker/splunk.yml:/tmp/defaults/default.yml
