{{ range .Values.applications }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-dotnet-{{ .name }}
  labels:
    app: demo-dotnet
    app.kubernetes.io/name: demo-dotnet
    app.kubernetes.io/component: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-dotnet
      app.kubernetes.io/name: demo-dotnet
      app.kubernetes.io/component: {{ .name }}
  template:
    metadata:
      labels:
        app: demo-dotnet
        app.kubernetes.io/name: demo-dotnet
        app.kubernetes.io/component: {{ .name }}
    spec:
      containers:
        - name: demo-dotnet-{{ .name }}
          image: {{ .image }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          readinessProbe:
            httpGet:
              path: "/health"
              port: 80
          {{- with .env }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ $.Values.aspnetcore.environment }}"
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{ end }}
